### ISSUE TITLE
Plugin is not using consistent tab/space setting with user settings

### ISSUE THREAD

**Issue by raph92** [mintlify/intellij-docs#25]
## Environment
**AI Doc Writer Version**: 1.0.10
**PyCharm Version**:  2021.3.2
**OS**: Manjaro 5.16.7
## Issue
When generating docs for any function the plugin defaults to tabs with causes errors.
## Example
![Screenshot_20220219_130336](https://user-images.githubusercontent.com/26060177/154813225-85231158-112b-4a68-8459-8f5db31a368b.png)

## Expectation
Ideally, the plugin should use settings consistent with the user settings

**Comment by raph92** [comment]
Actually, it looks like this is already a WIP in #22. Should I close this?

**Comment by emirkmo** [comment]
I came here to search for the same issue, I would not close until #22 is merged.

**Comment by hahnbeelee** [comment]
@raph92 @emirkmo v1.0.12 is out with a fix. Can you guys confirm that it's fixed on your guys' end?

**Comment by raph92** [comment]
> @raph92 @emirkmo v1.0.12 is out with a fix. Can you guys confirm that it's fixed on your guys' end?

Thank you @hahnbeelee, it's working!
