### ISSUE TITLE
Getting Error : Not Able to Generate Docs

### ISSUE THREAD

**Issue by milindbangar79** [mintlify/intellij-docs#32]
Hi,

I liked the idea of Doc Writer and downloaded on IntelliJ for my Java code.

But it always comes with error : Unable to generate docs: Please try again later or report the error to hi@mintlify.com.

Being on Enterprise network, cannot join Discord, hence raising the issue .

I tested on my personal copy of IntelliJ and it worked. 

Is there a call going out from Plugin, which I would think is blocked and hence the issue.

IntelliJ Version : 2021.2.4 , JDK 17

Thanks
Milind

**Comment by hahnbeelee** [comment]
Yes, unfortunately the plugin is dependent on calling an API point, so it's possible that it has been blocked. It's also possible that you could be on a later version of AI Doc Writer? The latest version is 1.0.13

**Comment by milindbangar79** [comment]
Thanks for the response. I am using version 1.0.13.

I believe we cannot open proxy for the endpoint and hence cannot use plugin our company.

I will however keep using on my personal repos.
